### ISSUE TITLE
Vekeerde programmering

### ISSUE THREAD

**Issue by TonVH** [tvgrabbers/tvgrabpyAPI#10]
Ik merk dat (m.n. NPO 1) er soms verkeerde programmagegevens (tijden, titel) worden opgehaald. De v2.2 haalt in die gevallen wel de goede op. Blijkbaar gebruiken beide verschillende bronnen. 

De oude/v2.2 gebruikt m.i. de juiste/beste bron.

**Comment by hikavdh** [comment]
Het is mij niet opgevallen. Kun je voorbeelden geven in de toekomst, want dan kan ik kijken wat er gebeurt.

**Comment by TonVH** [comment]
Begrijp het probleem.

Ik wist gisteren (toeval) dat aangegeven uitzending niet klopte. Heb toen de oude 2.2 gedraaid en die gaf de juiste informatie, weer 3.0 gedraaid en deze gaf foutieve. Heb er toen vanwege drukte niet aan gedacht de div. logfiles te bewaren.

Later op de dag nogmaals heel voorafgaande gedaan en toen gaven beide versies opeens dezelfde juiste programmering.

Zodra dit weer optreedt (en ik het geluk heb dit te merken) zal ik alle logfiles bewaren.

Gr,
