### ISSUE TITLE
How to TVHeadend v4.1.x?

### ISSUE THREAD

**Issue by schumi2004** [tvgrabbers/tvgrabpyAPI#15]
Hi,

Ik heb nooit eerder gebruik gemaakt van tv_grab_nl dus dacht bij het in gebruik nemen ervan maar meteen versie 3 te pakken.
Ik heb me wat ingelezen en wat test runs gedaan in een VM en dat leek allemaal naar wens te verlopen en nu wilde ik het naar mijn Synology brengen wat ook geen probleem hoeft te zijn.
Waar ik alleen tegen aanloop is hoe de data nu in TVHeadend ingelezen te krijgen?

Ik had al gelezen om voor TVH de use-only-cache optie te gebruiken en de normale run zonder.
En daar zit hem nu net het probleem. Voor zover ik kan zien heb ik in TVH geen invloed in hoe een extern script gerunt wordt, ik kan alleen maar een sock file uitlezen en dat is meteen het tweede probleem, hoe krijg ik de data naar de TVH sock ?

**Comment by hikavdh** [comment]
Ik vrees dat ik je naar een tvheadend forum oid moet doorsturen. Ik gebruik zelf MythTV en heb dus geen ervaring met tvheadend. Ik denk dat je om de  use-only-cache optie te gebruiken het in een shell script moet inpakken en dat vervolgens in tvheadend moet gebruiken. Bijvoorbeeld:
```
#!/bin/bash

/usr/bin/tv_grab_nl3.py $@  --use-only-cache
```

**Comment by schumi2004** [comment]
@hikavdh 
Ik zal het eens bij tvheadend navragen en mogelijk dat er nog wat tweakers zijn die er meer ervaring mee hebben, bedankt iig ;)
