### ISSUE TITLE
programmatitel verkeerd

### ISSUE THREAD

**Issue by marcelveldt** [tvgrabbers/tvgrabpyAPI#16]
Allereerst hartelijk dank voor deze tool, ik gebruik het al jaren en ben recent overgestapt op de nieuwe versie. Na enig configuratiewerk heb ik het inmiddels tot volle tevredenheid draaien. Top!

Vandaag viel me echter iets vreemds op.
Volgende week begint een nieuw seizoen van Prison Break op FOX die ik alvast in wilde stellen om op te nemen en tot mijn verbazing kon ik die niet vinden in de gids.

Wat blijkt... Op de 1 of andere manier wordt de serie nu onder de naam "Sequel" geplaatst.
De serie heet inderdaad Prison Break: Sequel maar ik denk dat de grabber nu onterecht de originele titel er ergens afsplitst.

Ik heb even gecheckt in de xmltv file en daar staat nu inderdaad de volgende vermelding:

```
<programme  start="20170405210000 +0200" stop="20170405220000 +0200" channel="0-440">
    <title  lang="nl">Sequel</title>
    <sub-title  lang="nl">Ogygia</sub-title>
    <desc  lang="nl">Dramaserie. Prison Break is terug en klaar voor zijn grootste ontsnapping ooit. De doodgewaande Michael blijkt nog in leven te zijn en zijn broer is klaar om hem te bevrijden. | Kijkwijzer: Let op met kinderen tot 12 jaar, programma bevat geweld, angst en grof taalgebruik.</desc>
 
```

Wat zou ik aan moeten passen om dit op te lossen ?
Mogelijk dat dit probleem ook bij andere series optreed, het valt me alleen nu bij deze ineens op.

De serie wordt a.s woensdag 5 april om 21:00 uitgezonden trouwens.

Alvast bedankt voor je hulp.

**Comment by hikavdh** [comment]
Dit is iets dat helaas vrij incidenteel gebeurd. Door de verschillende bronnen wordt soms vrijzinnig en in elk geval heel verschillend met titels/subtitels omgegaan. Soms worden ze samengevoegd of er wordt een generieke titel voor geplaatst zoals "KRO detectives" enz. In de vorige versie waren er al een aantal verschillende algoritmes om dit uit te filteren. In versie 3 zijn die grotendeels samengevoegd. 
Om te beginnen worden er bij het verwerken van elke bron tot 3 niveaus bepaald: groepstitel, titel en subtitel. Net als in versie 2 wordt wanneer er een ":" in de titel voorkomt, dit een serie is én er geen subtitel bekend is aangenomen dat dit om een titel/subtitel combinatie gaat. Er is wel eens gevraagd dit uit te breiden met een "," of ";", maar dat geeft nog meer valse hits. Vervolgens wordt bij het samenvoegen van de verschillende bronnen naar een gemene deler gezocht, waarbij twee van de drie overblijven. Helaas is dit algoritme nog niet perfect. 
Een verschil met versie twee is dat veel van deze filters op elke bron apart worden toegepast alvorens ze samen te voegen. Bij versie 2 gebeurde dit deels pas na het samenvoegen. Een nadeel is dat er dan dus vaker geen subtitel bekend is en er daar door iets meer kans is op valse hits.

Wat je kunt doen is de complete titel (dus "Prison Break: Sequel") toevoegen aan de "[no title split list]" lijst in `~/.xmltv/tv_grab_nl3_py.set`.
Op vergelijkbare wijze kun je via de "[remove groupname list]" en de "[rename title list]" lijst dit proces sturen. Dit bijvoorbeeld omdat ": Sequel" bij de ene bron wel en dan weer niet wordt toegevoegd. Je kunt dan:
``` 
Prison Break = Prison Break: Sequel
```
of 
``` 
Prison Break: Sequel = Prison Break
```
aan de "[rename title list]" toevoegen. De titel voor het "=" teken is case-insensitive, die erachter wordt letterlijk toegepast.

Ik kan deze titel ook aan de algemene lijst toevoegen, maar ik weet zo niet direct zeker of dit dan ook op bestaande installaties wordt toegepast. Ik dacht "[no title split list]" wel, maar "[remove groupname list]" en "[rename title list]" niet.

**Comment by marcelveldt** [comment]
Helemaal geweldig, ik ga er even mee stoeien. Bedankt voor je vlotte en uitgebreide reactie!

**Comment by marcelveldt** [comment]
Excuses voor de late reactie. Ik wilde nog even laten weten dat het probleem is opgelost. 
Het werkt nu perfect. Enige minpuntje wat ik kan noemen is dat het echt uren duurt om de data op te halen en dat het proces dan 100% van m'n cpu gebruikt maar dat ligt denk ik meer aan m'n NAS.

**Comment by hikavdh** [comment]
Heb je de laatste DataTreeGrab release https://github.com/tvgrabbers/DataTree/releases/tag/stable-1.3.3 al geïnstalleerd? Deze geeft een flinke snelheidsverbetering.
