### ISSUE TITLE
Tvheadend categories - Dutch television

### ISSUE THREAD

**Issue by martijnjagers** [tvgrabbers/tvgrabpyAPI#19]
Hi there, thanks for all efforts with this grabber! It is quite awesome, but I have one thing that does not work as well as I expected it to work. The categories / subcategories in tvheadend are empty for like 90% of the cases. 

I wondered if this was because of data going into the SQLite database was lacking or because of translation towards the xml coming from the database... It seems to be that for a LOT of programs this data does not arrive at the database... Is this a known issue?

I used to get EPG from EIT, which worked flawless for many channels, but was lacking logos, did not supply two weeks etc. But if this grabber is not able to deal properly with categories I don't know what's worse ;).

**Comment by hikavdh** [comment]
No, the database buffering does not change anything.
Let me shortly explain how it works. First we have all the different sources. Some have categories some not and those who have, have all their own interpretation. That's where the first translation layer comes in. It tries to translate all the different systems into one common system.
The second layer is optional. It is on by default but by setting cattrans to False you disable it. It is there so you can adapt it to your personal whishes and/or to the system your program uses. The default tables are designed towards MythTV. I never used TVheadend, so I do not know what it expects.
Another thing is that the XMLTV standard does not know subcategories, so this second layer translates category/subcategory couples to a single category. If you disable cattrans only the category is used. So for instance no difference between all kinds of Series or Movies. At any time the subcategories are added to the start of the description. 
If the default does not work for you, go to ~/.xmltv/tv_grab_nl3.set. Here you find all the translation tables your system uses and here you can adapt them.
