### ISSUE TITLE
tvheaded

### ISSUE THREAD

**Issue by filoor** [tvgrabbers/tvgrabpyAPI#20]
Hi,
I nhope you can help me.
Where is the xml file being saved
I have tvheadend on a raspberry pi dir: "/home/osmc/.hts/tvheadend"
and your program is on "/home/osmc/.xmltv"
if i run " tv_grab_nl3.py" program it will get the data
but how do i sow it in tveheadend.

Fetch statistics for 827 programms on 1 channels:
 Start time: 2017-05-22 10:17
   End time: 2017-05-22 10:36
   Duration: 0:18:53.408862
   255 page(s) fetched, of which 179 failed
     0 cache hits
   424 succesful ttvdb.com lookups
   100    failed ttvdb.com lookups
  Time/page: 4.44474063529 seconds

    49 page(s) fetched from theTVDB.com
     2 failure(s) on theTVDB.com

     6   base page(s) fetched from tvgids.tv
     0 detail page(s) fetched from tvgids.tv
     4 failure(s) on tvgids.tv

     4   base page(s) fetched from tvgids.nl
   228 detail page(s) fetched from tvgids.nl
   174 failure(s) on tvgids.nl

     0   base page(s) fetched from primo.eu
     0 detail page(s) fetched from primo.eu
     0 failure(s) on primo.eu

     0   base page(s) fetched from rtl.nl
     0 failure(s) on rtl.nl

     0   base page(s) fetched from npo.nl
     0 failure(s) on npo.nl

    11   base page(s) fetched from horizon.tv
     1 failure(s) on horizon.tv

     0   base page(s) fetched from humo.be
     0 failure(s) on humo.be

     4   base page(s) fetched from vpro.nl
     0 failure(s) on vpro.nl

     0   base page(s) fetched from nieuwsblad.be
     0 failure(s) on nieuwsblad.be

     0   base page(s) fetched from vrt.be
     0 failure(s) on vrt.be

     0   base page(s) fetched from oorboekje.nl
     0 failure(s) on oorboekje.nl

Waiting for all remaining threads to finish

![image](https://cloud.githubusercontent.com/assets/3647638/26299769/53cb8872-3edc-11e7-8f81-6a9ebaaf8d34.png)

**Comment by hikavdh** [comment]
Unless you specify a filename with the --output option the output is only send to the screen. See `tv_grab_nl3.py --help`. Try `tv_grab_nl3.py --use-only-cache --output <filename>` to not fetch anew but get the earlier fetched data.
For specifics on using it with tvheadend I refer to a tvheadend forum.
