### ISSUE TITLE
Crash on fetching euronews

### ISSUE THREAD

**Issue by winfried** [tvgrabbers/tvgrabpyAPI#21]
Hi,

I have since several day the following, recurring, crash:

`Now merging 82 programs from horizon.tv into 220 programs from Euronews
    (channel 17 of 61)

An unexpected error has occured in the Euronews (0-422) thread:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tvgrabpyAPI/tv_grab_channel.py", line 216, in run
    self.channel_node.merge_source(programs, index)
  File "/usr/local/lib/python2.7/dist-packages/tvgrabpyAPI/tv_grab_channel.py", line 1140, in merge_source
    check_gaps(group_slots[index], True)
  File "/usr/local/lib/python2.7/dist-packages/tvgrabpyAPI/tv_grab_channel.py", line 979, in check_gaps
    add_to_list(add_to_end, pp, is_groupslot)
  File "/usr/local/lib/python2.7/dist-packages/tvgrabpyAPI/tv_grab_channel.py", line 957, in add_to_list
    pn.scandate = programs[index]['scandate']
IndexError: list index out of range

If you want assistence, please attach your configuration and log files!
     /var/lib/mythtv/.xmltv/tv_grab_nl3_py.conf
     /var/lib/mythtv/.xmltv/tv_grab_nl3_py.log
Waiting for all remaining threads to finish
`

The config for euronews is:
`Euronews;14;0-422;;euronews;;422;;24443943027;;;euronews;euronews;;;;4;euronews_1.png
`

What I tried to fix it:
- update to the latest API
- clear cache
But still the crash occurs. If you need some more info or something else, please let me know.

**Comment by hikavdh** [comment]
This is a real bug. I did not properly adapt the code when moving it into a sub function. 
Change at line 957:
`                pn.scandate = programs[index]['scandate']`
to
`                pn.scandate = pp['scandate']`
should do the trick.
Most of the times pp will be the same as programs[index] but this is a rare case on rechecking groupslots, that obviously never before got a hit. (Called from line 1140 in stead of from line 1133). I'll add the fix to the next release.

**Comment by winfried** [comment]
Thanks a lot for your lightning fast response, that did the trick!

**Comment by hikavdh** [comment]
There is a new [version 1.0.7](https://github.com/tvgrabbers/tvgrabpyAPI/releases/tag/beta-1.0.7-p20170625), although for now still in beta. It also requires you updating DataTreeGrab to [version 1.4](https://github.com/tvgrabbers/DataTree/releases/tag/beta-1.4.0-p20170625).
It includes this fix.
