### ISSUE TITLE
Na migratie geen .XMLfile meer.

### ISSUE THREAD

**Issue by TonVH** [tvgrabbers/tvgrabpyAPI#22]
Ik heb alles van oude naar nieuwe iMac overgezet. Ogenschijnlijk werkt alles maar de .XML file staat op lengte 0. 
Enige foutmelding die ik ontdek is "Cannot open url https://web-api-pepper.horizon.tv/oesp/api/NL/nld/web/listings/" en ook wordt er geen mail meer verzonden na afloop.

Is er iets wat ik handmatig moet doen omdat het nu op een nieuw systeem draait?

**Comment by hikavdh** [comment]
Dit zou heel wel een netwerk probleem kunnen zijn. 
- Voeg een log bij.
- Draai het een keer in een console om de foutmelding voor het niet mailen te zien. Die melding kan niet in het log komen, omdat alvorens te mailen dit eerst gesloten moet worden.

**Comment by hikavdh** [comment]
Controleer je DNS
