### ISSUE TITLE
name 'DataDef_Convert' is not defined

### ISSUE THREAD

**Issue by marcelveldt** [tvgrabbers/tvgrabpyAPI#23]
Just upgraded to the latest release and now have this error.
I tried looking for a class with a similar name in the source (assuming a typo) but could't find it.

> Traceback (most recent call last):
>   File "/volume2/Software/xmltv/tvgrabpy/tv_grab_nl3.py", line 108, in <module>
>     import sys, locale, tvgrabpyAPI
>   File "/volume2/Software/xmltv/tvgrabpy/tvgrabpyAPI/__init__.py", line 8, in <module>
>     from tv_grab_config import *
>   File "/volume2/Software/xmltv/tvgrabpy/tvgrabpyAPI/tv_grab_config.py", line 111, in <module>
>     import tv_grab_IO, tv_grab_fetch, tv_grab_channel, pytz
>   File "/volume2/Software/xmltv/tvgrabpy/tvgrabpyAPI/tv_grab_IO.py", line 2865, in <module>
>     class DD_Convert(DataDef_Convert):
> NameError: name 'DataDef_Convert' is not defined

**Comment by hikavdh** [comment]
Have you also upgraded DataTreeGrab!?

**Comment by marcelveldt** [comment]
Yes, I did, but can do it again just to be safe

**Comment by hikavdh** [comment]
The DataTreeGrab version is checked on startup, so why then on your system can't it find the conversion Class? Can you give a full log?

**Comment by hikavdh** [comment]
I see now, that check is three lines after importing the rest of tv_grab_y_API. So it seems it is still working with the old DataTreeGrab. Did you run both setups properly under python 2.7?

**Comment by marcelveldt** [comment]
I guess I screwed up myself.
Ran both setups again and now it seems to be working.

Sorry for the trouble!
