### ISSUE TITLE
stuck on SSL error with horizon.tv

### ISSUE THREAD

**Issue by tonyschuite** [tvgrabbers/tvgrabpyAPI#24]
Hi there, 

I am getting an error when running the configure command:
Cannot open url https://web-api-pepper.horizon.tv/oesp/api/NL/nld/web/channels/

kind regards
tony

full log:
root@tvh:/tmp/tvgrabpyAPI # python tv_grab_nl3.py --configure
Loaded the English texts file
Using config file: /etc/tvgrabpyAPI/tv_grab_nl3_py.conf
File: "/etc/tvgrabpyAPI/tv_grab_nl3_py.conf" not found or could not be accessed.
  Downloading tv_grab_API.json...
  Downloading tv_grab_nl.json...
The channel/source matching data is newer!
Nickelodeon and Spike changes, use the following:
         0-89: Nickelodeon 24/7.
        0-467: Spike 24/7.
1-nickelodeon: Combined Nickelodeon/Spike.
PRIME is now Play More.
HBO and Fox Life have closed.
Omroep Brabant is now 24/7 on Canal Digitaal, use 0-114.
While we are working on a renewed source-file for the new npo.nl site
this source is disabled! Further news follows in the comming days.
Wild FM changed name to Wild Hitradio.
The npo.nl source has been reactivated, but as the channelids
have all changed you need to run --configure to use it.
It now gives basic listings for all the NPO channels for up to 2 weeks.
Unfortunatly only start time and titel and no longer for the regional channels.
Creating config file: /etc/tvgrabpyAPI/tv_grab_nl3_py.conf
Verifying the database
Cannot open url https://web-api-pepper.horizon.tv/oesp/api/NL/nld/web/channels/
Unable to get channel info from horizon.tv
Not all channel info could be retrieved.
Try again in 15 minutes or so; or disable the failing source.
Waiting for all remaining threads to finish

**Comment by hikavdh** [comment]
Why do you think it to be an SSL error?
Can you open the link in your browser? I can!

**Comment by tonyschuite** [comment]
yeah, I can too... but this one is running off a freenas system and when using fetch or wget i get returned an SSL error:

wget https://web-api-pepper.horizon.tv/oesp/api/NL/nld/web/channels/
--2017-08-26 22:19:20--  https://web-api-pepper.horizon.tv/oesp/api/NL/nld/web/channels/
Resolving web-api-pepper.horizon.tv (web-api-pepper.horizon.tv)... 2a00:fd0:1012:110::115, 83.98.5.91
Connecting to web-api-pepper.horizon.tv (web-api-pepper.horizon.tv)|2a00:fd0:1012:110::115|:443... failed: No route to host.
Connecting to web-api-pepper.horizon.tv (web-api-pepper.horizon.tv)|83.98.5.91|:443... connected.
OpenSSL: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Unable to establish SSL connection.

**Comment by hikavdh** [comment]
So I guess you are missing the needed ssl libraries on that machine. But it does retrieve the sourcefiles from git-hub, which also is https. 
Also I see "No route to host" which could point to a dns or firewall problem.

**Comment by hikavdh** [comment]
Which Python version are you using? The minimum version of 2.7.9 is especially for https support.

**Comment by hikavdh** [comment]
I look better at your post and the first failure is on ipv6, which you can ignore. But my guess would still be some firewall issue. Do you have special rules for your NAS on your router? does your NAS run iptables?

**Comment by tonyschuite** [comment]
I am using Python 2.7.13 so no problems there
I don't have any specific settings concerning IP tables or anything. I can also correctly fetch the git source so that should not work if there where any SSL issues on my system... I will see if i can troubleshoot some more.
