### ISSUE TITLE
Apparent problems with tvgids.tv

### ISSUE THREAD

**Issue by pensionado** [tvgrabbers/tvgrabpyAPI#26]
It appears there are problems with tvgids,tv, saw many 404 not found (in terminal window, noit in the log !!) on fetches from that source and run finished with:
_An unexpected error has occured in the tvgids.tv thread:
While fetching the base pages
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tvgrabpyAPI/tv_grab_fetch.py", line 2007, in run
    self.config.infofiles.check_new_channels(self, self.config.source_channels)
  File "/usr/local/lib/python2.7/dist-packages/tvgrabpyAPI/tv_grab_IO.py", line 2609, in check_new_channels
    source.get_channels()
  File "/usr/local/lib/python2.7/dist-packages/tvgrabpyAPI/tv_grab_fetch.py", line 2471, in get_channels
    if isinstance(channel_list, list):
UnboundLocalError: local variable 'channel_list' referenced before assignment

If you want assistence, please attach your configuration and log files!
     /home/pi/.xmltv/tv_grab_nl3_py.conf
     /home/pi/.xmltv/tv_grab_nl3_py.log
Waiting for all remaining threads to finish_

Output appears to be only partial.

**Comment by hikavdh** [comment]
Was this on running --configure ? Please enclose full log.

**Comment by pensionado** [comment]
No a rerun of my daily run. This is the log
[tv_grab_nl3_py.zip](https://github.com/tvgrabbers/tvgrabpyAPI/files/1491804/tv_grab_nl3_py.zip)
running it again now, to see if it was a hiccup in the data.

**Comment by pensionado** [comment]
Must have been a data  hiccup, daily run finished normally this time.

**Comment by hikavdh** [comment]
Do you have `write_info_files = True` enabled in your config? Because else I do not understand why it did run check_new _channels. If you do not need it for debugging you better remove it or set it to False. That code part I mainly use myself so is less well maintained not to give fatal errors.
Anyhow it was caused by a failure to retrieve the channels list from tvgids.nl
