### ISSUE TITLE
No output at all after midnight tonight after daily run

### ISSUE THREAD

**Issue by pensionado** [tvgrabbers/tvgrabpyAPI#27]
After daily run (twice) no output at all for any station in xml output after midnight tonight, despite that log indicates data was retrieved.  This issue looks similar to earlier reported problem for canvas, but now ALL stations are affected. Enclosed log and xml output.

**Comment by pensionado** [comment]
Log files:
[Documents.zip](https://github.com/tvgrabbers/tvgrabpyAPI/files/1501085/Documents.zip)

**Comment by hikavdh** [comment]
I see at first glance what looks like a normal xmltv file?
Please also enclose your configuration file

**Comment by pensionado** [comment]
Found the problem, I used to use xml.output3 in the .xmltv directory, instead of using the output option, not realising that that is only created if you have write_info_files set to true, and I switched that off 2 days ago on your recommendation, so my xml output never got updated anymore, now using the --output, I get what I expected.
