### ISSUE TITLE
Negeren van programma's met bepaalde titels

### ISSUE THREAD

**Issue by rsenden** [tvgrabbers/tvgrabpyAPI#33]
In recente runs van tvgrabpyAPI zie ik dat horizon.tv dummy programma-informatie teruggeeft, bijvoorbeeld:

` Added from      horizon.tv:#23 Aug 06:00 - 23 Aug 07:00: Zender verstrekt geen informatie:--- Genre: Unknown.`

Aangezien tvgrabpyAPI dit als valide programma-informatie ziet, wordt de informatie op deze dagen/tijdstippen niet meer verder aangevuld met informatie van sources met lagere prioriteit, zoals tvgids.tv.

Is het mogelijk om dit soort programma-informatie te negeren (bijvoorbeeld negeren van alle programma's met als titel 'Zender verstrekt geen informatie' of vergelijkbare configureerbare titels), zodat tvgrabpyAPI alsnog de gegevens van een andere source probeert op te halen?

**Comment by hikavdh** [comment]
Onjuist, dit wordt als een gat gezien dat door andere bronnen in gevuld kan worden

**Comment by rsenden** [comment]
Voor mijn informatie, kun je aangeven hoe tvgrabpyAPI bepaalt dat dit als gat gezien wordt, en waarom deze gegevens dan alsnog in de uiteindelijke tvguide.xml terecht komen (ik zie in TVHeadEnd en Kodi liever geen programma, dan een dummy-programma met als titel 'Zender verstrekt geen informatie')?

**Comment by hikavdh** [comment]
In de json data staat een lijst met titels, die we indien nodig uitbreiden. Totdat het gat gevuld wordt, blijft het als zodanig aanwezig in de listing. Als je meer data over jouw merge proces wilt hebben, voeg dan in je configuratie toe:
write_info_files = True
Er worden dan in je .xmltv een paar extra dat bestanden aangemaakt, die info geven over het proces.
