### ISSUE TITLE
Horizon.tv episode numbers

### ISSUE THREAD

**Issue by mitchellklijs** [tvgrabbers/tvgrabpyAPI#37]
Hi,

Horizon.tv provides some weird episode numbers for some programmes.

When running `tv_grab_nl3.py` **without** `--disable-source 5` (5 = horizon.tv), the episode number of, for example, the NOS Journaal looks like this: `<episode-num system="xmltv_ns"> . 821185866 . </episode-num>`.
When running `tv_grab_nl3.py` **with** `--disable-source 5` (5 = horizon.tv), the episode number of, for example, the NOS Journaal looks like this: `<episode-num system="xmltv_ns"> . 82 . </episode-num>`.

I can see in the horizon JSON response that this episode number is stated there. So the data is retrieved correctly. So I don't think there is any way to fix that.
Is it possible in any way to disable the episode numbers from horizon for specific programmes? Or to prefer certain sources for episode numbering?

**Comment by hikavdh** [comment]
Not at the moment. The value occurring in most sources wins. If several values have the same occurrence the priority of the sources decides. So if the 82 values is offered by more then one source it will win. 
However I am also surprised, I thought I had blocked episode numbers that are above a certain value.

**Comment by hikavdh** [comment]
Maybe that was for another source. In the datadef you can set max and min values and max text length. If those limits are then exceeded the value is thrown out. That way I for instance catch a description in the subgenre field on tvgids.tv. I might have to set such a limit on the episode number from horizon.tv. As I thought I had, but it could be I did so on one of the Flemish sources.

**Comment by mitchellklijs** [comment]
The limit is quite a clever idea. 
I cannot think of another situation at the moment where prioritizing a certain sources' episode number would make sense. So implementing the limit would solve this issue.

I think there is indeed no limit to the episode number coming from Horizon (https://github.com/tvgrabbers/sourcematching/blob/master/sources/source-horizon.tv.json#L166).

**Comment by hikavdh** [comment]
All ties on selecting are managed by the source priority. This priority is mostly based on which source has the best start and stop time for that channel and managed by my colleague. You however can always set your own prime-source for any channel. The only value with its own priority source is the description. Be sure to set `always_use_json` to False if you want to set those values or your settings will be ignored.

**Comment by hikavdh** [comment]
I will look at this max value sometime soon.

**Comment by mitchellklijs** [comment]
> All ties on selecting are managed by the source priority. This priority is mostly based on which source has the best start and stop time for that channel and managed by my colleague. You however can always set your own prime-source for any channel. The only value with its own priority source is the description. Be sure to set `always_use_json` to False if you want to set those values or your settings will be ignored.

Yeah, I don't think it is necessary to add a priority source for the episode number if the ridiculously large episode numbers can be ignored.

**Comment by hikavdh** [comment]
Done, set the max on 365
