### ISSUE TITLE
Errors on Synology NAS

### ISSUE THREAD

**Issue by alex341** [tvgrabbers/tvgrabpyAPI#40]
My NAS updated its OS and (as usual) this gave problems with the grabber. Usually, I just installed it again and everything worked fine. But now I get errors...
I installed the latest version of the grabber (1.0.9), but as soon as I run "tv_grab_nl3.py --configure --language nl", I get errors: Error creating message text, error loading language file, error creating message text and that several times in a row.

What is going wrong?

**Comment by hikavdh** [comment]
This is probably some rights problem where your user cannot access the language files in your python directory. Under linux these are in /usr/lib/python2.7/site-packages/tvgrabpyAPI/texts

**Comment by alex341** [comment]
Who should have access? The daily run is done under admin and the test was also done as admin. I should think admin should have the correct rights, not? 
The owner is root and group is root. Which should both be?

**Comment by hikavdh** [comment]
The user running it, but further I don't know. What I remember from earlier discussion about weird behavior by your NAS OS is that it does weirdly fiddle with directories and rights ánd that admin is not root. Specific NAS OS questions you'll have to ask on their forum.

**Comment by alex341** [comment]
Hika, you are top! I checked previous problems and indeed the directory rights were the problem then. I changed it and it is scheduled to run now... and so far no problems. First run after a new install might take a few hours, but I will inform you about the result. Tnx again for the quick respons!
