### ISSUE TITLE
Extremely slow and data-errors in tvgids.nl

### ISSUE THREAD

**Issue by alex341** [tvgrabbers/tvgrabpyAPI#42]
Recently I reinstalled the grabber on my Synology NAS. With a bit of help from Hika, I managed to get it running again, with the new 1.0.9 version. 

In my setup, I get an e-mail every time a tv_grab run is completed. In the past it took upto two hours for getting all the data. Now, with the new install the first mail came after 5 days!!! What is with that? 

In the mail, a lot of errors were shown, such as:
     0 resterend in de npo.nl queue om te verwerken
   223 resterend in de tvgids.nl queue om te verwerken
     0 resterend in de primo.eu queue om te verwerken
    59 resterend in de tvgids.tv queue om te verwerken
Er is een fout: "Unable to parse the HTML data. Invalid dataset!"
   opgetreden bij het inlezen van een detail DataTree voor tvgids.nl
De pagina 68395091 leverde geen data op
Kan de pagina niet lezen. https://www.tvgids.nl/tv/null/68139181/: code=404: Not Found
De pagina 68139181 leverde geen data op
Er is een fout: "Unable to parse the HTML data. Invalid dataset!"
   opgetreden bij het inlezen van een detail DataTree voor tvgids.nl
De pagina 68395141 leverde geen data op

Nu wordt SBS 6(xmltvid=0-36) van tvgids.tv opgehaald
    (zender 10 van 16) voor dag 13 van 14.
Er is een fout: "Unable to parse the HTML data. Invalid dataset!"
   opgetreden bij het inlezen van een detail DataTree voor tvgids.nl
De pagina 68395471 leverde geen data op
Er is een fout: "Unable to parse the HTML data. Invalid dataset!"
   opgetreden bij het inlezen van een detail DataTree voor tvgids.nl
De pagina 68138701 leverde geen data op
Er is een fout: "Unable to parse the HTML data. Invalid dataset!"
   opgetreden bij het inlezen van een detail DataTree voor tvgids.nl
De pagina 68395421 leverde geen data op

What is happening? I got the latest DataTree version (1.0.4).

**Comment by rsenden** [comment]
See https://github.com/tvgrabbers/tvgrabpyAPI/issues/41, looks like we both have the same issue.
