### ISSUE TITLE
is it ready for end-user?

### ISSUE THREAD

**Issue by bam80** [tvgrabbers/tvgrabpyAPI#44]
Hello,
I'm wonder if it ready for user? What sites are already supported?

**Comment by hikavdh** [comment]
To my knowledge there is only the Dutch/Flemish frontend.

**Comment by bam80** [comment]
Ok thanks. Is there any forum to ask for support more countries?
And also how would you estimate the project possibilities compared with WebGrab++?
Thanks

**Comment by hikavdh** [comment]
I do not know WebGrab++ so I can not compare.
We have created a developers forum. So far I have not had any requests for help.
But it is not extremely complicated, all that is needed are definitions of how and where to get the data and someone to track and update on changes in those data sources. Especially webpages get regularly updated, json sources on average are stable for years Our API will handle the rest.
To start with, which locality are you talking about?
Do you know of sites or json sources that could supply the data for your locality?
Are you willing to try and more important are you willing to support it for at least a year, but better longer? 
The most work will be to first set it up. After that it is mostly monitoring and occasionally investing one or two hours. 
I can assist and you can either create your own data source location or we can host it. Once there is a first working frontend, I will add it and push an update.

**Comment by hikavdh** [comment]
Also, but that can be done later, if you want the program to respond in your language, you can create and add your own language file.

**Comment by bam80** [comment]
I'm interested in parsing following sites described in WG language:
https://github.com/SilentButeo2/webgrabplus-siteinipack/blob/master/siteini.pack/Russia/tv.yandex.ru.ini
https://github.com/SilentButeo2/webgrabplus-siteinipack/blob/master/siteini.pack/Russia/tv.mail.ru.ini

**Comment by bam80** [comment]
@hikavdh so how do you think, would parsing the mentioned sites with tvgrabpyAPI produce amount of data/code comparable with WG siteini files above?

**Comment by hikavdh** [comment]
Have you read the wiki on creating your own frontend?
As Russian is Babylonian to me I can not estimate on the possibilities with your two sites, but anything that is there can be extracted, so anything WG gets we can get. 
Try creating a basic frontend: https://github.com/tvgrabbers/tvgrabpyAPI/wiki/frontend, https://github.com/tvgrabbers/tvgrabpyAPI/wiki/creating_a_grabber_datafile.
If you have that you can start on the first source file.
