### ISSUE TITLE
Source "Humo" fails

### ISSUE THREAD

**Issue by WimObiwan** [tvgrabbers/tvgrabpyAPI#46]
Their original API located at
https://www.humo.be/api/epg/humosite/schedule/main/2020-02-01
seems disabled since last night.  
`tvgrabpyAPI --configure` fails with error `De url: http://www.humo.be/api/epg/humosite/channels gaf een JSON fout: No JSON object could be decoded`.
The title for most of the programs is "Download onze nieuwe app!"

It seems they now have a newer one locate at:
https://www.humo.be/tv-gids/api/v2/broadcasts/2020-02-01

**Comment by dingo35** [comment]
I have the same problem; it makes that the --configure run fails, so tv_grab_nl3_py.conf is not written; and that means disabling the failing source is impossible, because 
tvgrabpyAPI --disable-source 6 reports : 
"Re-run me with the --configure flag."

Sort of a catch 22 here ...

**Comment by hikavdh** [comment]
The change has been noted and I have temporarily disabled the source. I'll look at a solution in the coming days.

**Comment by dingo35** [comment]
Problem remains, but now with another source:

>  Creating config file: /var/lib/mythtv/.xmltv/tv_grab_nl3_py.conf
Verifying the database
Cannot open url http://www.nieuwsblad.be/tv-gids
Unable to get channel info from nieuwsblad.be
Not all channel info could be retrieved.
Try again in 15 minutes or so; or disable the failing source.
Waiting for all remaining threads to finish
```
Wouldnt it be smarter to let the software write the .conf file ALWAYS (and not only if ALL channel info from ALL sources could be retrieved), and give a warning when info is missing? It is then up to the user to re-run the software with the --configure flag some time later, or just ignore the warning if the source is of no interest to you (as is the case with me)?

**Comment by hikavdh** [comment]
Testing the nieuwsblad source works, so I think it was just temporarily.

**Comment by dingo35** [comment]
Thanks for your quick response hikavdh!

I might have been geofenced, I am in the US. But even through my VPN it doesn't work.
This is strange, because my webbrowser is perfectly able to access https://www.nieuwsblad.be/tv-gids .
Is it perhaps a problem that the script is trying http://www.nieuwsblad.be/tv-gids instead of the https page?

**Comment by cctl01** [comment]
> 
> 
> The change has been noted and I have temporarily disabled the source. I'll look at a solution in the coming days.

Any updated file where the source was disabled? I can not create the config eigther with the most recent git pull.

**Comment by hikavdh** [comment]
I just checked and saw that primo which already was not giving any data for some time now is completely gone. It is now also disabled. I will see to get a humo replacement this weekend.

**Comment by hikavdh** [comment]
Well, this is going to be tricky, as the problem seems to be caused by a blocking cooky pop-up. Both there old and new sites are still up and running, but without the acceptance cooky... 
Maybe there is an option like on tvgids.nl with cookieoptin = True.
The needed cookies are pwv = 1 and pws = functional|analytics
If anybody has an idea?

**Comment by hikavdh** [comment]
We have come up with two possible solutions, only both need a code update. So it will take more time. I'll keep you informed and once there is a stable update, you'll see it in your log.

**Comment by hikavdh** [comment]
See: https://github.com/tvgrabbers/tvgrabpyAPI/releases/tag/beta-1.0.10-p20200202

**Comment by hikavdh** [comment]
And an update: https://github.com/tvgrabbers/tvgrabpyAPI/releases/tag/beta-1.0.10-p20200206

**Comment by dingo35** [comment]
Thanks for all your work Hika. However, I'm still not able to create a .conf file:

> Creating config file: /var/lib/mythtv/.xmltv/tv_grab_nl3_py.conf
Verifying the database
Cannot open url http://www.nieuwsblad.be/tv-gids
Unable to get channel info from nieuwsblad.be
Not all channel info could be retrieved.
Try again in 15 minutes or so; or disable the failing source.
Waiting for all remaining threads to finish


Wouldn't it make sense to create the .conf file for the part that it _can_ retrieve? I'm not even interested in nieuwsblad.be program info.....

**Comment by hikavdh** [comment]
Have you tried `tv_grab_nl3.py --configure --disable-source 8`

**Comment by dingo35** [comment]
Thanks for that tip, works like a charm now!

There are showing two error messages: 

> Loaded the English texts file
Using config file: /var/lib/mythtv/.xmltv/tv_grab_nl3_py.conf
Error while reading a line in the [Configuration] section of config file /var/lib/mythtv/.xmltv/tv_grab_nl3_py.conf:u'disable_source = 8'
Error while reading a line in the [Channels] section of config file /var/lib/mythtv/.xmltv/tv_grab_nl3_py.conf:u'NPO Soul &amp; Jazz;11;4-297;;;;;rad6;;;;;;;;npo-soul-en-jazz;7;radio_channel/361/logo/NPO_RD2_Logo_RGB_S_J_rood.png'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tvgrabpyAPI/tv_grab_config.py", line 1698, in read_config
    self.channels[chanid] = tv_grab_channel.Channel_Config(self, chanid, unicode(channel[0]).strip(), int(channel[1]))
ValueError: invalid literal for int() with base 10: 'Jazz'

..but they are not blocking and easy to disable by deleting the appropriate lines from the .conf file.

Thank you for your help!!

**Comment by hikavdh** [comment]
That's what it said! "Try again in 15 minutes or so; or disable the failing source."

The first error I'll look into. The other comes from somehow `&` in NPO Soul & Jazz being written in HTML representation `&amp;` which should not happen.
