### ISSUE TITLE
tvgrabpy looping after exception in sources.

### ISSUE THREAD

**Issue by pensionado** [tvgrabbers/tvgrabpyAPI#47]
My daily tv program update this morning was looping, which happens from time to time, but even after repeated manual starts it kept failing, I suspect the culprit is this:
`Loaded the English texts file
Using config file: /home/geert/.xmltv/tv_grab_nl3_py.conf
  Downloading tv_grab_API.json...
  Downloading tv_grab_nl.json...
Exception in thread source-primo.eu:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/tvgrabpyAPI/tv_grab_fetch.py", line 2037, in run
    detail_idx = self.config.detail_sources.index(self.proc_id)
ValueError: 9 is not in list

Verifying the database
`
Suspect that problem originates from the downloaded files outside my control. Please advise which documentation you need.

**Comment by JanCeuleers** [comment]
In order not to make this purely a "me too" comment (but nevertheless: I am also experiencing this problem with the same symptoms and therefore probably a different selection of channels) let me add a little information about the symptoms I see:

The above error message appears quite quickly after the grabber starts. Despite the exception the grabber then proceeds but does not appear ever to terminate, consuming a fair amount of CPU. I have had to kill it.

Removing the program cache does not have any effect.

**Comment by vanesp** [comment]
Sorry. Have to make the "me too" comment. Moi aussi...

**Comment by hikavdh** [comment]
Yes I, I see it too, although not the error Pensionado is mentioning or any error. It seems to be the ever again recurring problem on disabling a source. Grrr.

**Comment by hikavdh** [comment]
OK, weirdly enough the error with me does not show in the log, but does on the screen and I have identified it as coming from primo being a detail source. I removed the pointer from the primo sourcefile. Possibly now this error won't occur anymore, but I'm still testing and fixing it for the soon to come update to make the new humo work.

**Comment by hikavdh** [comment]
Fixed.

**Comment by vanesp** [comment]
Thanks
