### ISSUE TITLE
NPO Episode Numbers

### ISSUE THREAD

**Issue by mitchellklijs** [tvgrabbers/tvgrabpyAPI#48]
Since a couple of weeks the episode numbers for NPO channels don't work anymore (they are missing). I'm not sure what changed and I can't figure out what the problem is.
All other channels (that I've checked) have no problems.

**Comment by hikavdh** [comment]
I've seen other issues with the NPO channels, but haven't as jet investigated. I guess one of the sources has changed part of their format. I'll check soon.

**Comment by kyl416** [comment]
Can you give some examples of which shows and channels are you looking at? Most of the usual shows on NPO 1, 2 and 3 have season and episode numbers in the grab I did today.

Also, have you updated to the latest version of tvgrabpyAPI and run --configure afterwards? Most of the NPO season and episode numbers come from Humo and they made changes to their site that require the new version and a rerun of configure to associate the new station ids.

**Comment by mitchellklijs** [comment]
Hi,

I've done a clean install and only ran for NPO 1 as a test case. The configuration file has the lines you mention for the NPO channels.
In my grab it has not a single episode number (only if I enable TTVDB there are a couple that are found). There are some `<previously-shown/>` tags, but none of them have any attributes.

So that is quite weird then!

------

My test case:

- Clean install, only modification to the configuration file is uncommenting the line for NPO 1.
- Clear cache, just to be sure: `tv_grab_nl3.py --clear_cache`
- Ran the following command: `tv_grab_nl3.py -W xmltv.xml --disable-ttvdb --verbose`

Attached are the script output and the resulting XMLTV file (in txt, because XML uploads are not allowed ;) ):

- [output.txt](https://github.com/tvgrabbers/tvgrabpyAPI/files/4335516/output.txt)
- [xmltv.xml.txt](https://github.com/tvgrabbers/tvgrabpyAPI/files/4335520/xmltv.xml.txt)

**Comment by kyl416** [comment]
Can you post your tv_grab_nl3_py.log, tv_grab_nl3_py.set and tv_grab_nl3_py.conf files?

I noticed it didn't fetch any detail pages from humo and only fetched 8 detail pages from tvgids.nl and 16 detail pages from NPO.nl. You might have to tweak a setting in the .set file to get it to fetch additional details.

**Comment by mitchellklijs** [comment]
Hereby.

[tv_grab_nl3_py.zip](https://github.com/tvgrabbers/tvgrabpyAPI/files/4337402/tv_grab_nl3_py.zip)

**Comment by kyl416** [comment]
Try replacing everything under the [genres to get detail pages for] in tv_grab_nl3_py.set with "all" so it looks like this:
```
[genres to get detail pages for]
all
```

The default values skips things like kids shows, some other series and things missing genres entirely.

**Comment by mitchellklijs** [comment]
I've just ran it, but there is only one program that has an episode number. See attachment.

[xmltv.zip](https://github.com/tvgrabbers/tvgrabpyAPI/files/4339649/xmltv.zip)

**Comment by kyl416** [comment]
For some reason you're getting a lot of failures on VPRO which is another source of episode numbers. Try increasing the global_timeout value in your tv_grab_nl3_py.conf file to something like 60 and lowering the value of max_simultaneous_fetches to 4.

**Comment by mitchellklijs** [comment]
I've tried it, but with the same results... 

It reports:

```
2020-03-16 21:11:44 CET:    278 page(s) fetched, of which 0 failed and 0 returned no data
2020-03-16 21:11:44 CET:      0 cache hits
2020-03-16 21:11:44 CET:      0 succesful ttvdb.com lookups
2020-03-16 21:11:44 CET:      0    failed ttvdb.com lookups
2020-03-16 21:11:44 CET:   Time/page: 2.14297342446 seconds
2020-03-16 21:11:44 CET:      0 page(s) fetched from theTVDB.com
2020-03-16 21:11:44 CET:      0 failure(s) on theTVDB.com
2020-03-16 21:11:44 CET:      6   base page(s) fetched from tvgids.tv, of which 0 returned no data
2020-03-16 21:11:44 CET:      0 detail page(s) fetched from tvgids.tv, of which 0 returned no data
2020-03-16 21:11:44 CET:      0 failure(s) on tvgids.tv
2020-03-16 21:11:44 CET:      6   base page(s) fetched from tvgids.nl, of which 0 returned no data
2020-03-16 21:11:44 CET:     13 detail page(s) fetched from tvgids.nl, of which 0 returned no data
2020-03-16 21:11:44 CET:      0 failure(s) on tvgids.nl
2020-03-16 21:11:44 CET:      6   base page(s) fetched from npo.nl, of which 0 returned no data
2020-03-16 21:11:44 CET:    226 detail page(s) fetched from npo.nl, of which 0 returned no data
2020-03-16 21:11:44 CET:      0 failure(s) on npo.nl
2020-03-16 21:11:44 CET:      6   base page(s) fetched from humo.be, of which 0 returned no data
2020-03-16 21:11:44 CET:      1 detail page(s) fetched from humo.be, of which 0 returned no data
2020-03-16 21:11:44 CET:      0 failure(s) on humo.be
2020-03-16 21:11:44 CET:      0   base page(s) fetched from rtl.nl, of which 0 returned no data
2020-03-16 21:11:44 CET:      0 failure(s) on rtl.nl
2020-03-16 21:11:44 CET:      5   base page(s) fetched from horizon.tv, of which 0 returned no data
2020-03-16 21:11:44 CET:      0 failure(s) on horizon.tv
2020-03-16 21:11:44 CET:      5   base page(s) fetched from vpro.nl, of which 0 returned no data
2020-03-16 21:11:44 CET:      0 failure(s) on vpro.nl
2020-03-16 21:11:44 CET:      2   base page(s) fetched from nieuwsblad.be, of which 0 returned no data
2020-03-16 21:11:44 CET:      0 failure(s) on nieuwsblad.be
2020-03-16 21:11:44 CET:      0   base page(s) fetched from primo.eu, of which 0 returned no data
2020-03-16 21:11:44 CET:      0 failure(s) on primo.eu
2020-03-16 21:11:44 CET:      0   base page(s) fetched from vrt.be, of which 0 returned no data
2020-03-16 21:11:44 CET:      0 failure(s) on vrt.be
2020-03-16 21:11:44 CET:      0   base page(s) fetched from oorboekje.nl, of which 0 returned no data
2020-03-16 21:11:44 CET:      0 failure(s) on oorboekje.nl
```

I don't see any errors about a timeout anymore.

**Comment by kyl416** [comment]
For some reason it's still only fetching the detail page for one program from Humo.be. One difference is that you don't have a prefered_description value set for NPO 1 like I do, maybe that's changing the behavior for how it handles detail sources.

Can you try modifying the entry for NPO 1 in your tv_grab_nl3_py.conf file under the # Channel specific settings other then the above or the default:
```
# NPO 1
[Channel 0-1]
prime_source = 7
prefered_description = 7
```

**Comment by hikavdh** [comment]
One thing about detail pages. It will on every run fetch only one detail page per programme. If more are available from other sources, they will get fetched on a following run. One exception is the NPO source if it is also the prime-source. To get proper start and end times the detail page is needed. So those will all get prefetched.

**Comment by hikavdh** [comment]
So the behavior is dependent on whether some of the detail pages are already available from the database.

**Comment by mitchellklijs** [comment]
I've changed the config as suggested and ran the command twice in a row this time (without clearing the cache in between). This time it had two episode numbers, not a very satisfactory result ;). 

In the log I see that it did a lot of fetches to tvgids.nl (the second time). If I manually go to the site I do see the episode listing. Are we sure that it can succesfully retrieve those?

Log from the second run:
```
Detail statistics for NPO 1 (channel 1 of 1)
    55 cache hit(s)
    26 excluded by genre
   184 detail fetch(es) from npo.nl.
   304 detail fetch(es) from tvgids.nl.
    12 detail fetch(es) from tvgids.tv.
     2 detail fetch(es) from humo.be.
     0 failure(s)
     7 without detail info

     0 left in the npo.nl queue to process
     0 left in the tvgids.nl queue to process
     0 left in the tvgids.tv queue to process
     0 left in the humo.be queue to process


Execution complete.

Fetch statistics for 603 programms on 1 channels:
 Start time: 2020-03-16 23:22
   End time: 2020-03-16 23:34
   Duration: 0:11:40.504670
   527 page(s) fetched, of which 0 failed and 0 returned no data
    55 cache hits
     0 succesful ttvdb.com lookups
     0    failed ttvdb.com lookups
  Time/page: 1.32923087287 seconds

     0 page(s) fetched from theTVDB.com
     0 failure(s) on theTVDB.com

     6   base page(s) fetched from tvgids.tv, of which 0 returned no data
    12 detail page(s) fetched from tvgids.tv, of which 0 returned no data
     0 failure(s) on tvgids.tv

     6   base page(s) fetched from tvgids.nl, of which 0 returned no data
   304 detail page(s) fetched from tvgids.nl, of which 0 returned no data
     0 failure(s) on tvgids.nl

     6   base page(s) fetched from npo.nl, of which 0 returned no data
   184 detail page(s) fetched from npo.nl, of which 0 returned no data
     0 failure(s) on npo.nl

     2   base page(s) fetched from humo.be, of which 0 returned no data
     2 detail page(s) fetched from humo.be, of which 0 returned no data
     0 failure(s) on humo.be

     0   base page(s) fetched from rtl.nl, of which 0 returned no data
     0 failure(s) on rtl.nl

     1   base page(s) fetched from horizon.tv, of which 0 returned no data
     0 failure(s) on horizon.tv

     1   base page(s) fetched from vpro.nl, of which 0 returned no data
     0 failure(s) on vpro.nl

     1   base page(s) fetched from nieuwsblad.be, of which 0 returned no data
     0 failure(s) on nieuwsblad.be

     0   base page(s) fetched from primo.eu, of which 0 returned no data
     0 failure(s) on primo.eu

     0   base page(s) fetched from vrt.be, of which 0 returned no data
     0 failure(s) on vrt.be

     0   base page(s) fetched from oorboekje.nl, of which 0 returned no data
     0 failure(s) on oorboekje.nl
```

**Comment by kyl416** [comment]
Unfortunately tvgids.nl doesn't provide episode numbers or titles in their json feed, which also affects their mobile iOS and Android apps. I sent them a feature request to add them to their android app, hopefully they eventually provide them. Their HTML pages have them, but it's generated dynamically so when we were using them it mostly resulted in failures and made the fetch process take hours with all the retries.


That default behavior of only fetching one detail source might be a problem, especially when only the detail pages for humo have the season numbers that are needed to generate the xmltv_ns numbering. We do have a regex to attempt to get the numbers from VPRO, but not all programs provide it. Thetvdb is hit or miss and requires nearly exact matching, which can be a problem for shows where episode titles get translated into Dutch.

Maybe we should tweak it to also pay attention to the "provides" entries in the source files so it will fetch additional detail pages that would potentially have information like season, episodecount, etc that other detail sources don't provide.

**Comment by mitchellklijs** [comment]
Are you sure that the season and episode numbers are generated dynamically for the HTML pages? I've just tried doing a basic curl request for one of the episodes and it does return the HTML with the episode number. Maybe they've changed it? Or do you mean something else?

The tweak you propose could be valuable!

The weird thing, however, is that it worked just fine until the last couple of weeks. I didn't change any of the configuration. Very strange!
So, for you it does include the episode numbers?

**Comment by kyl416** [comment]
The HTML pages are generated dynamically when you fetch the page and cached for a time on their server. So doing a grab with the HTML pages resulted in a bunch of initial failures and retries that made the grab take several hours, especially when you got further out and were attempting to fetch additional days that might haven't have been visited recently.

Yeah for me it does, but I also already have the details cached which is probably why it fetched the additional detail pages. Up until a few weeks ago humo had a different API and all the information was available via the basic fetches, with their new API only their detail pages have the episode and season numbers.

Edit: Correction, they now have them in the json feed! I'll see if we can add them.

**Comment by kyl416** [comment]
Looking at it they still don't provide episode/aflevering titles, but the json feed now has season, episode and episodecount

**Comment by kyl416** [comment]
I just pushed an update to sourcematching so your next fetch should grab them. You'll have to clear your cache first otherwise they'll only appear for newly fetched programs.

**Comment by hikavdh** [comment]
Well done Kyle!

**Comment by kyl416** [comment]
If anyone wants to save time and not clear the other detail sources like humo, npo and tvgids.tv open up a command prompt, navigate to the folder that has your program_cache3.db file and run the following
```
sqlite3 program_cache3.db
```
And then enter the following within the console
```
DELETE from `programdetails` WHERE `sourceid` IS "3";
VACUUM;
.exit
```

**Comment by hikavdh** [comment]
You better use the --clear_source option in tv_grab_nl3.py
`tv_grab_nl3.py --clear_source 3 `
It will also clear base pages but editing the database yourself could result in nasty results

**Comment by hikavdh** [comment]
For instance you will leave orphaned records in some of the other tables!

**Comment by kyl416** [comment]
One more tweak incoming, I forgot to include the int parameter

**Comment by mitchellklijs** [comment]
This seems to have fixed the problem! I've now ran the command a couple of times in a row and I now have quite a lot episode numbers.
I'll test it further the following days.
