### ISSUE TITLE
Hangs

### ISSUE THREAD

**Issue by Tr71** [tvgrabbers/tvgrabpyAPI#50]
Hi all,

When running tv_grab_nl3 at the end it hangs on: 

`Detail statistics for Nickelodeon / Spike (virtual) (channel 64 of 65)
     0 cache hit(s)
     0 excluded by genre
   228 without details in cache`

What can i be doing wrong?

**Comment by hikavdh** [comment]
Please include your configuration file and log. Also relevant is whether you can reproduce the situation.
