### ISSUE TITLE
Encoding/locale issue in retrieved EPG data

### ISSUE THREAD

**Issue by Laibalion** [tvgrabbers/tvgrabpyAPI#54]
Not entirely sure if it's an issue with tvgrabpyAPI or with tvheadend tbh, but here goes.
If the EPG data retrieved contains some non ANSI characters, like 'é', the character in tvheadend gets mangled to a '?'

**Comment by hikavdh** [comment]
EPG has nothing to do with any grabber, it is send by the cable provider together with the channel and extracted by your program. If you do not mean EPG but the data retrieved from internet by tvgrabpyAPI, then this probably is an issue with tvheadend or your operating system. All export is encoded as set in your OS which normally is utf-8 on Linux and windows-1252 on Windows.

**Comment by Laibalion** [comment]
Indeed, I didn't mean the EPG broadcasted by the provider, but mean the EPG in tvheadend, which contains data from the grabber. Sorry about the confusion.
The device running tvheadend and tvgrabpyapi is a Synology NAS, so I'd assume it's utf-8. 
Eitherway, both utf-8 and windows-1252 are able to encode é, so not sure what is causing this.
Looking at the grab log, the logs contain the correct characters, but that doens't guarantee of course the data sent to tvheadend is also right.
But if you say that the grabber handles it correct, I trust you and it's a tvheadend issue
