### ISSUE TITLE
Tvgrabber stopped working after json errorin sourcefile for source-horizon.tv

### ISSUE THREAD

**Issue by pensionado** [tvgrabbers/tvgrabpyAPI#57]
This morning tvgrabber was looping, and after running in a terminal window following errors showed up:

Loaded the English texts file
Using config file: /home/geert/.xmltv/tv_grab_nl3_py.conf
  Downloading tv_grab_API.json...
  Downloading tv_grab_nl.json...
  Downloading source-horizon.tv.json...
The url: https://raw.githubusercontent.com/tvgrabbers/sourcematching/master/sources/source-horizon.tv.json gave JSON error: Expecting object: line 888 column 1 (char 45467)
No valid source description for 5 found. Disableing it!
Verifying the database

An unexpected error has occured in the  thread:
While fetching the base pages
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tvgrabpyAPI/tv_grab_fetch.py", line 2119, in run
    self.init_channel_source_ids()
  File "/usr/local/lib/python2.7/dist-packages/tvgrabpyAPI/tv_grab_fetch.py", line 2274, in init_channel_source_ids
    if self.source_data['alt-url-code'] != None and self.sourcedbdata['use_alt_url']:
KeyError: u'alt-url-code'

If you want assistence, please attach your configuration and log files!
     /home/geert/.xmltv/tv_grab_nl3_py.conf
     /home/geert/.xmltv/tv_grab_nl3_py.log
Waiting for all remaining threads to finish

On inspection it appears there is a curly bracket missing at the end.

Log and config attached
[config_log.zip](https://github.com/tvgrabbers/tvgrabpyAPI/files/9835876/config_log.zip)

**Comment by hikavdh** [comment]
I see it. My colleague forgot a "}" to finish the adapted channels section for horizon
