### ISSUE TITLE
BBC First: time offset

### ISSUE THREAD

**Issue by JanCeuleers** [tvgrabbers/tvgrabpyAPI#60]
The guide data produced by the grabber for channel BBC First is offset by an hour: programs are broadcast 1 hour later than the guide data suggests.

**Comment by hikavdh** [comment]
I guess the site it is retrieved from made a mistake with the timezone difference and we will have to wait for them to fix it.

**Comment by kyl416** [comment]
All of the BBC First sources currently have the same times, and they match what's on the BBC Benelux website.

BBC First did have a schedule change last week that several sources like tvgids.nl along with their own website didn't show until the day it went into effect, so maybe you have some outdated data in your program_cache.

**Comment by JanCeuleers** [comment]
Thanks.

It seems that I have a bigger issue: I initially misdiagnosed the situation as guide data that is 1 hour off. In fact the guide data is completely wrong, and when I first looked at it there happened to be an instance of a show at a 1-hour offset.

Is BBC First the same across the Benelux? I'm in Belgium and the adverts are clearly aimed at Belgium. Of course it's possible to insert different ads for different markets, but is the actual programming also different?

I've now verified that the guide data on my cable provider's STB aligns with reality, and also with BBC Benelux's website. But I don't know whether that website shows a different lineup depending on the visitor's geo-IP.

So to investigate this further: how can I find out from which source tv_grab_nl3_py obtains guide data for this channel?

I am invoking the grabber as follows:

/usr/local/bin/tv_grab_nl3.py --disable-source 6 --disable-source 7 --disable-source 1 --config-file tv_grab_nl3_py.conf --output tv_grab_nl3_py.out

**Comment by kyl416** [comment]
Belgium has a different schedule. Rerun --configure and in your tv_grab_nl3_py.conf file use "BBC First Vlaanderen" under "Vlaams Overig".

Also, if you're in Belgium, you shouldn't disable source 6 as Humo is the main source for many of the Vlaanderen feeds like VTM, Comedy Central, Nickelodeon, MTV, FOX, TLC, Discovery, Nat Geo and others.

**Comment by JanCeuleers** [comment]
Thanks for the hint about the different versions of BBC First; that's what I needed to fix this issue.
