### ISSUE TITLE
tvgrab no longer works due to lack of valid sources

### ISSUE THREAD

**Issue by pensionado** [tvgrabbers/tvgrabpyAPI#61]
Since yesterday tvgrab no longer functions due to lack of sources, this is the log:
""
Loaded the English texts file
Using config file: /home/geert/.xmltv/tv_grab_nl3_py.conf
  Downloading tv_grab_API.json...
  Downloading tv_grab_nl.json...
  Downloading source-tvgids.tv.json...
No valid source description for 1 found. Disableing it!
  Downloading source-rtl.nl.json...
No valid source description for 2 found. Disableing it!
  Downloading source-tvgids.nl.json...
No valid source description for 3 found. Disableing it!
  Downloading source-npo.nl.json...
No valid source description for 4 found. Disableing it!
  Downloading source-horizon.tv.json...
No valid source description for 5 found. Disableing it!
  Downloading source-humo.be.json...
No valid source description for 6 found. Disableing it!
  Downloading source-vpro.nl.json...
No valid source description for 7 found. Disableing it!
  Downloading source-nieuwsblad.be.json...
No valid source description for 8 found. Disableing it!
  Downloading source-primo.eu.json...
No valid source description for 9 found. Disableing it!
  Downloading source-vrt.be.json...
No valid source description for 10 found. Disableing it!
  Downloading source-virtual.nl.json...
No valid source description for 11 found. Disableing it!
  Downloading source-oorboekje.nl.json...
No valid source description for 12 found. Disableing it!

An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tvgrabpyAPI/tv_grab_config.py", line 142, in grabber_main
    x = config.validate_commandline()
  File "/usr/local/lib/python2.7/dist-packages/tvgrabpyAPI/tv_grab_config.py", line 765, in validate_commandline
    self.write_opts_to_log()
  File "/usr/local/lib/python2.7/dist-packages/tvgrabpyAPI/tv_grab_config.py", line 2741, in write_opts_to_log
    log_array.append(u'  prime_source = %s (%s)\n' % (src_id, self.channelsource[src_id].source))
KeyError: -1
[tv_grab_nl3_py.zip](https://github.com/tvgrabbers/tvgrabpyAPI/files/12135742/tv_grab_nl3_py.zip)

""

**Comment by hikavdh** [comment]
First, when have you last run a fresh configure? I see mentioning of old obsolete sources.
Second my guess is a local disk problem. It looks like downloaded json files don not get saved. So check if your disk is not out of space or inodes, check if the user running the script has sufficient rights and worst case that your disk is not reaching EOL.
Another possibility is (temporarily) problems with your net connection.

**Comment by pensionado** [comment]
It was indeed intermittent network problems. The day before the problem started I had a router failure and was still busy recovering from that. I suspect not fully functional ipv6 was the culprit. Considered this is a user issue.
