### ISSUE TITLE
Horizon.tv problem

### ISSUE THREAD

**Issue by TonVH** [tvgrabbers/tvgrabpyAPI#7]
Tried this version as I understood elsewhere this would solve the probe but does not. Still get error message.

========
iMac:~ tonio$ python /Applications/_EyeTV/xmlgen3/tv_grab_nl3.py --config-file /Applications/_EyeTV/xmlgen3/xmlgen3.config --output /Applications/_EyeTV/XMLgen3/XMLgen3.xml --configure
Loaded the English texts file
Using config file: /Applications/_EyeTV/xmlgen3/xmlgen3.config
File: "/Applications/_EyeTV/xmlgen3/xmlgen3.config" not found or could not be accessed.
  Downloading tv_grab_API.json...
  Downloading tv_grab_nl.json...
The channel/source matching data is newer!
Nickelodeon and Spike changes, use the following:
         0-89: Nickelodeon 24/7.
        0-467: Spike 24/7.
1-nickelodeon: Combined Nickelodeon/Spike.
PRIME is now Play More.
HBO and Fox Life have closed.
Omroep Brabant is now 24/7 on Canal Digitaal, use 0-114.
Wild FM changed name to Wild Hitradio.
Creating config file: /Applications/_EyeTV/xmlgen3/xmlgen3.config
Verifying the database
Cannot open url https://web-api-pepper.horizon.tv/oesp/api/NL/nld/web/channels/ <-------
Unable to get channel info from horizon.tv
Not all channel info could be retrieved.
Try again in 15 minutes or so; or disable the failing source.
Waiting for all remaining threads to finish

**Comment by hikavdh** [comment]
It's a pity. Kyle tried and said it worked. So then the only options left are finding an update for the CA certificates or disabling the source until Apple issues a (security) update.

**Comment by antoniong** [comment]
Python 3.6 geinstalleerd maar na "python3 /Applications/_EyeTV/XMLgen3/tv_grab_nl3.py --configure --config-file /Applications/_EyeTV/XMLgen3/XMLgen3.config" komt er de foutmelding:
=====
Traceback (most recent call last):
  File "/Applications/_EyeTV/XMLgen3/tv_grab_nl3.py", line 108, in <module>
    import sys, locale, tvgrabpyAPI
  File "/Applications/_EyeTV/XMLgen3/tvgrabpyAPI/__init__.py", line 8, in <module>
    from tv_grab_config import *
ModuleNotFoundError: No module named 'tv_grab_config'
=====
Binnen tvgrabpyapi is een file tv_grab_config.py aanwezig.

Wellicht onbelangrijk maar bevreemd mij is dat als ik bovenstaande met python (en dan dus v2) draai dat ik dan deze foutmelding net krijg maar wel weer de welbekende foutmelding over Horizon.tv waarvan ik dacht dat dit met v3 opgelost zou zijn.

Persoonlijk zou ik gewoon horizon.tv willen uitschakelen maar zolang ik in v3 niet --configure kan draaien weet ik ook de "id" niet.

Wat betreft oplossing Kyle. Ik heb die 3 links bekeken maar kan daar echt geen garen van spinnen.

Zou het op prijs stellen als iemand een voor mij bruikbaar antwoord heeft hoe dit op een Mac werkend te krijgen.

**Comment by hikavdh** [comment]
Heb je sudo ./setup.py install gedraaid? Zoals in de readme en in https://github.com/tvgrabbers/tvgrabpyAPI/wiki/installation. Het programma zegt zichzelf niet te kennen! Dus is niet of niet juist geïnstalleerd!

**Comment by antoniong** [comment]
Gedaan, maar probleem blijft:

```
iMac:XMLgen3 tonio$ sudo python3 ./setup.py install
Traceback (most recent call last):
  File "./setup.py", line 12, in <module>
    from tvgrabpyAPI import version, __version__
  File "/Applications/_EyeTV/XMLgen3/tvgrabpyAPI/__init__.py", line 8, in <module>
    from tv_grab_config import *
ModuleNotFoundError: No module named 'tv_grab_config'
```

**Comment by hikavdh** [comment]
Je hebt Python 2.7 nodig! 2.7.9 of groter! Mogelijk zou het werken met python 3, maar setup.py is geschreven voor 2.7 en installeert in dat module pad! Je kunt python 2 en 3 niet mixen maar wel naaste elkaar installeren en gebruiken. Blijkbaar heb je überhaupt geen python 2?

**Comment by hikavdh** [comment]
Ik kijk nog eens verder wat je had ingetypt!
Waarom type je sudo python3 ./setup.py install?
- Ten eerste hoef je python onder Linux en aanverwant niet apart aan te roepen. Dit moet alleen afhankelijk van hoe het geïnstalleerd is onder Windows. (of python in het pad staat)
- Ten tweede roep je python3 aan voor een python2 installatie, die vervolgens zelf python2 aanroept, zoals in de header van het script staat. Wanneer je niet weet welke van de twee je moet hebben, gebruik dan python. De modules van elke Python versie staan in een apart module pad.
python2, python3 en python zijn simlinks, die linken naar respectievelijke jouw actieve python 2.x.x installatie,  jouw actieve python 3.x.x installatie en naar de door jouw geselecteerde favoriet van die twee.
Om het nog iets ingewikkelder te maken, kun je python 3.3, 3.4, 3.5 en 3.6 ook naast elkaar installeren. Theoretisch zou je daarvoor ook aparte simlinks kunnen maken.

**Comment by antoniong** [comment]
Als ik "setup.py install" dan krijg ikeen foutmelding terwijl als ik expliciet "python setup.py install" doe dan gaat e.e.a goed. Uiteraard zou ik dat kunnen oplossen door het in "path = " te zetten maar ik voe er niets voor om bij elke update of herinstallatie dit soort zaken te moeten aanpassen. Houd liever system en user gescheiden.

Ik gebruik Python 3 omdat ik uit een eerder bericht de indruk had gekregen dat met Python 3 het horizon.tv zou zijn opgelost.

Ga straks e.e.a. met Python v2 weer uitproberen.

**Comment by antoniong** [comment]
Ik heb e.e.a. opnieuw gedl'ed en geinstalleert. Om spraakverwarring te vermijden doe ik voorlopig alles basic.

Output setup.py install:
```
iMac:XMLgen3 tonio$ python setup.py install
running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
changing mode of /Library/Frameworks/Python.framework/Versions/2.7/bin/tv_grab_nl3.py to 755
changing mode of /Library/Frameworks/Python.framework/Versions/2.7/bin/tv_grab_test_json.py to 755
changing mode of /Library/Frameworks/Python.framework/Versions/2.7/bin/tv_grab_test_source.py to 755
running install_data
running install_egg_info
Removing /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tv_grab_py_API-1.0.6-py2.7.egg-info
Writing /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tv_grab_py_API-1.0.6-py2.7.egg-info
iMac:XMLgen3 tonio$
```
Ziet er volgens mij goed uit.

Vervolgens "python tv_grab_nl3.py --configure gedraad:
```
iMac:XMLgen3 tonio$ python /Applications/_EyeTV/XMLgen3/tv_grab_nl3.py --configure
Loaded the English texts file
Using config file: /Users/tonio/.xmltv/tv_grab_nl3_py.conf
File: "/Users/tonio/.xmltv/tv_grab_nl3_py.conf" not found or could not be accessed.
  Downloading tv_grab_API.json...
  Downloading tv_grab_nl.json...
The channel/source matching data is newer!
Nickelodeon and Spike changes, use the following:
         0-89: Nickelodeon 24/7.
        0-467: Spike 24/7.
1-nickelodeon: Combined Nickelodeon/Spike.
PRIME is now Play More.
HBO and Fox Life have closed.
Omroep Brabant is now 24/7 on Canal Digitaal, use 0-114.
Wild FM changed name to Wild Hitradio.
Creating config file: /Users/tonio/.xmltv/tv_grab_nl3_py.conf
Verifying the database
Cannot open url https://web-api-pepper.horizon.tv/oesp/api/NL/nld/web/channels/
Unable to get channel info from horizon.tv
Not all channel info could be retrieved.
Try again in 15 minutes or so; or disable the failing source.
Waiting for all remaining threads to finish
iMac:XMLgen3 tonio$ 
```
Dit gaat dus niet goed. Allereerst het Horizon.net probleem maar dat is m.i. minder relevant. belangrijker is dat "/Users/tonio/.xmltv/tv_grab_nl3_py.conf" niet wordt aangemaakt. De log zegt weliswaar "creating ......" maar de file is (nergens) op de HD te vinden.

Dit blijkt ook wanneer "python /Applications/_EyeTV/XMLgen3/tv_grab_nl3.py " gedraaid wordt:
```
iMac:XMLgen3 tonio$ python /Applications/_EyeTV/XMLgen3/tv_grab_nl3.py 
Loaded the English texts file
Using config file: /Users/tonio/.xmltv/tv_grab_nl3_py.conf
File: "/Users/tonio/.xmltv/tv_grab_nl3_py.conf" not found or could not be accessed.
Re-run me with the --configure flag.
Trying to fall back on /etc/tvgrabpyAPI/tv_grab_nl3_py.conf.
File: "/etc/tvgrabpyAPI/tv_grab_nl3_py.conf" not found or could not be accessed.
Re-run me with the --configure flag.
Waiting for all remaining threads to finish
iMac:XMLgen3 tonio$ 
```
De enige "...conf" file die op de HD te vinden is, is deze "tv_grab_nl3_py.conf.log".  Inhoud = terminal outpur hierboven.

Vervolgens heb ik de conf file van v2.2 gecopieerd naar "tv_grab_nl3.py.conf" en dat blijkt wel te werken.
**Echter betwijfel ik of dit wel de juiste methode is.** 

Ook is het zonnet probleem nog steeds aanwezig. En als ik met "--show-detail-sources' draai dan:
```
Loaded the English texts file
Using config file: /Applications/_EyeTV/XMLgen3/XMLgen3.conf
  Downloading tv_grab_API.json...
  Downloading tv_grab_nl.json...
The available detail sources are: 
  1: tvgids.tv
  3: tvgids.nl
  9: primo.eu
The channel/source matching data is newer!
Nickelodeon and Spike changes, use the following:
         0-89: Nickelodeon 24/7.
        0-467: Spike 24/7.
1-nickelodeon: Combined Nickelodeon/Spike.
PRIME is now Play More.
HBO and Fox Life have closed.
Omroep Brabant is now 24/7 on Canal Digitaal, use 0-114.
Wild FM changed name to Wild Hitradio.
Run with "--configure" to implement it
Waiting for all remaining threads to finish
Verifying the database
iMac:XMLgen3 tonio$ 
```
**Waardoor ik dus niet met "--disable-source <ID>" kan draaien.**

**Comment by hikavdh** [comment]
"tv_grab_nl3.py --show-sources" en het is mogelijk dat horizon de tweede keer goed gaat. Horizon heeft twee verschillende URLs die ze elke paar weken wisselen. Mogelijk stond de verkeerde als default.
En wanneer een van de bronnen faalt wordt er geen configuratie aangemaakt.

**Comment by pensionado** [comment]
Having the same problem  no conf files created on running "tv_grab_nl3.py --show-sources" I get:

_tv_grab_nl3.py --show-sources
Loaded the English texts file
Using config file: /home/pi/.xmltv/tv_grab_nl3_py.conf
File: "/home/pi/.xmltv/tv_grab_nl3_py.conf" not found or could not be accessed.
Re-run me with the --configure flag.
Trying to fall back on /etc/tvgrabpyAPI/tv_grab_nl3_py.conf.
File: "/etc/tvgrabpyAPI/tv_grab_nl3_py.conf" not found or could not be accessed.
Re-run me with the --configure flag.
Waiting for all remaining threads to finish_

So this version is unusable (ran --configure, noth ass user and root same result see attached log.
[tv_grab_nl3_py.txt](https://github.com/tvgrabbers/tvgrabpyAPI/files/760841/tv_grab_nl3_py.txt)

**Comment by antoniong** [comment]
Had same problem. Solved it by taking the config from v2.2. Worked fine.

**Comment by hikavdh** [comment]
Horizon.tv is source 5, so if that source keeps failing, as it seems to do on the current Mac-OS version, run with --disable-source 5. I'll see if I can make --show-sources also work before there is a configuration file.
Antonio's solution will indeed work as long as the line:
# configversion: 2.220
is present at the top. It is still capable to interpret older configuration files. Whenever you next run --configure it will get converted.
