### ISSUE TITLE
DataTreeGrab soms importerror

### ISSUE THREAD

**Issue by TonVH** [tvgrabbers/tvgrabpyAPI#8]
Ik heb het geheel werkend en in een .command file gezet. Als ik die file start of door een double click of door Terminal te openen en hem daarin te starten dan werkt alles prima.

Echter als ik de .command file in Launchitems zet dan komt er bij de start de melding "ImportError: No module named DataTreeGrab" m.a.w. hij vind DTG niet.

Enig idee waar ik moet zoeken?

**Comment by hikavdh** [comment]
Ik ken de details niet bij apple, maar waar het op lijkt is dat in het tweede geval met een beperkte omgeving gewerkt wordt. Mogelijk kun je dit opvangen door met een shellscript te werken en dat shellscript aan te roepen.

#!/bin/bash
<en hier jouw opdrachtregel(s)>

en dit opslaan als bijvoorbeeld tv_grab_nl3.sh
