### ISSUE TITLE
Verschillen v3  en v2.2

### ISSUE THREAD

**Issue by TonVH** [tvgrabbers/tvgrabpyAPI#9]
Beide config files zijn identiek, idem de CLI.

1.  Toch is er een (ontzettend groot) verschil tussen de hoeveelheid informatie. Waar v2.2 voor de volle 14 dagen alle informatie laat zien is dit bij v3 voor vrijwel alle zenders veel beperkter.

2.  Ook opvallend is dat v2.2 aan 1 stuk door doorloppt terwijl v3 (altijd na Veronica/Disney XD vele minuten stilstaat.

Volledigheidshalve heb ik beide logfiles alsmede .config (beide zijn identiek) bijgesloten.

[log v2.2.txt](https://github.com/tvgrabbers/tvgrabpyAPI/files/763382/log.v2.2.txt)
[log v3.txt](https://github.com/tvgrabbers/tvgrabpyAPI/files/763386/log.v3.txt)
[Config.txt](https://github.com/tvgrabbers/tvgrabpyAPI/files/763388/Config.txt)

**Comment by hikavdh** [comment]
1. Dit heb ik gezien en ik heb nog geen tijd gehad om daarnaar in detail te kijken. Dit heeft waarschijnlijk of met tvgids.tv of met horizon.tv te maken. Dit zijn de twee bronnen die, naast rtl.nl het verst in de toekomst gaan.
2. Dat is schijn. Het hangt van je log_level af of er iets te rapporteren is, maar hij gaat wel door. 

De eerst twee weken of zo draait hij ook iets langer totdat de database goed gevuld is. Buiten wat al in de database aanwezig is, haalt hij maximaal 3 dagen per bron op, waaronder in elk geval vandaag. Dus elke dag gaat hij iets verder de toekomst in tot aan het maximum wat jij vraagt of 14 dagen. Aangezien voor rtl.nl alles in een keer opgehaald wordt is dat er wel direct voor 14 dagen.

**Comment by TonVH** [comment]
Duidelijk, mijn dank.

**Comment by hikavdh** [comment]
Ik heb inmiddels een oorzaak ontdekt voor het minder ver in de toekomst doorlopen van de data voor verschillende zenders. Dit is nu gefixed. Vannacht zou dit goed moeten gaan! De data van tvgids.tv werd wel opgehaald, maar werd door een klein foutje in de json bestanden niet meegenomen in het eind resultaat.
